ktor {
  deployment {
    port = 8080
    host = "0.0.0.0"
  }
}

database {
  url = "jdbc:postgresql://localhost:5433/taskprocessor_db"
  driver = "org.postgresql.Driver"
  user = "taskprocessor"
  password = "taskprocessor"
  maximumPoolSize = 10
}

cors {
  allowedHosts = ["localhost:3000", "localhost:8080"]
  development = true
}

processing {
  workerCount = 2

  useMockAi = true
;   useMockAi = ${?PROCESSING_USE_MOCK_AI}

  useInMemoryRepository = true
;   useInMemoryRepository = ${?PROCESSING_USE_IN_MEMORY_REPOSITORY}
}